API_ID: 16596628
API_HASH: 421764a823ee2dff786d413aea09959f
BOT_TOKEN: 5791754081:AAGqw45HHKBWCpkJaM-LithfZmOQIIXhrSo


MONGO_URL: mongodb+srv://anonuser:pCuymJvSt77OT3Ic@cluster0.kxrwyuz.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-18174.c275.us-east-1-4.ec2.cloud.redislabs.com
REDIS_PORT: 18174
REDIS_PASS: A9UshnXmWWF3At5i9D00Vd5SjlcZ6zII

SESSION_API_ID: 11197200
SESSION_API_HASH: e569a3f232f49667be19490e6f69b8c9
SESSION_STRING: 1BVtsOHEBuyw7RQDPFHny0H1YsTs3gMuz0IcXeVZPYH8yTzqb8qCySD0889cDyaeBYIR7u9nS0Lm4WF18WdDtXmlm7VzZc7pL2Z7okldpXWmB_rIj95DuQm_RkGuV6czjqWZub56xn1n6jyUM_z7Kf7YV_oqsHKG9qgjQLJcOq0ML0fLgP51Dygp84kTua2_rDbrqcXWRxWBDCofG0eWO4IdfdC_1fOiES6RIsnnNKSJtQrxUeho13twXi9C8lpXMe3slKJVUU0u_NJbuQg1ujZswBNBm3fesqSoSnt0w142DZe3rPfehoSpJnr997UElUh7De59vlurfwK9nCdRP99lrApjG0sI=
ADMINS: 5136746907

OWNER: 5383908433
OWNER: 5136746907
OWNER: 5410546502

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT:  
# LOG_CHAT: -1001657108198
LOG_CHAT: -1001786848035



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

